<a href="https://colab.research.google.com/github/ChinmayKumarT/python-libraries/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [513]:
import numpy as np

In [514]:
myarr = np.array([[3,6,32,7]], np.int8)
# int8 = 8bits and 1 byte
# int32 = 32bits and 4 byte
# int64 = 64bits and 8 byte
# use numpy type reference

In [515]:
myarr[0,1]

np.int8(6)

In [516]:
myarr.dtype

dtype('int8')

## Array creation : Conversion from other Python structures

In [517]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [518]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [519]:
listarray.dtype

dtype('int64')

In [520]:
listarray.shape

(3, 3)

In [521]:
listarray.size


9

## Array creation : Intrinsic NumPy array creation functions

In [522]:
zeros = np.zeros((2,5))

In [523]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [524]:
zeros.dtype

dtype('float64')

In [525]:
zeros.shape

(2, 5)

In [526]:
zeros.size

10

In [527]:
rng = np.arange(15)
#give n-1 values

In [528]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [529]:
lspace = np.linspace(1,50,5)
#syntax =start,stop,total values should be present in the output
#gives equal space between values

In [530]:
lspace

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [531]:
emp = np.empty([2,2])
#allocates the array which can be assigned values later

In [532]:
emp

array([[2.25206743e-315, 0.00000000e+000],
       [2.28591099e-315, 2.32779353e-315]])

In [533]:
emp1 = np.empty_like(lspace)
#copy the size of the given arrgument

In [534]:
emp1

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [535]:
id = np.identity(5)
#creates identity matrix of the size given

In [536]:
id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [537]:
id.shape

(5, 5)

In [538]:
id.size

25

In [539]:
rarr = np.arange(100)
rshape = rarr.reshape(2,50)
# reshape arrgument should be equal to the size of the original array

In [540]:
rshape

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [541]:
arr = rarr.ravel()
# brings back to normal

In [542]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [543]:
x = [[2,3,2],[4,3,1],[2,4,1]]
xarr = np.array(x)

In [544]:
xarr

array([[2, 3, 2],
       [4, 3, 1],
       [2, 4, 1]])

In [545]:
xarr.sum(axis=0)
# 0 = column

array([ 8, 10,  4])

In [546]:
xarr.sum(axis=1)
# 1 = row

array([7, 8, 7])

In [547]:
xarr.T
#transpose

array([[2, 4, 2],
       [3, 3, 4],
       [2, 1, 1]])

In [548]:
xarr.flat
#gives iterator

In [549]:
for i in xarr.flat:
    print(i)

2
3
2
4
3
1
2
4
1


In [550]:
xarr.ndim
#gives dimension

2

In [551]:
xarr.nbytes

72

In [552]:
one = np.array([1,3,1,4,6,34])


In [553]:
one.argmax()

np.int64(5)

In [554]:
one.argmin()

np.int64(0)

In [555]:
one.argsort()

array([0, 2, 1, 3, 4, 5])

In [556]:
xarr

array([[2, 3, 2],
       [4, 3, 1],
       [2, 4, 1]])

In [557]:
xarr.argmin()

np.int64(5)

In [558]:
xarr.argmax()

np.int64(3)

In [559]:
xarr.argmin(axis=0)

array([0, 0, 1])

In [560]:
xarr.argmin(axis=1)

array([0, 2, 2])

In [561]:
xarr.argmax(axis=0)

array([1, 2, 0])

In [562]:
xarr.argmax(axis=1)

array([1, 0, 1])

In [563]:
xarr.sort(axis=0)

In [564]:
xarr

array([[2, 3, 1],
       [2, 3, 1],
       [4, 4, 2]])

In [565]:
xarr.sort(axis=1)

In [566]:
xarr

array([[1, 2, 3],
       [1, 2, 3],
       [2, 4, 4]])

In [567]:
xarr.ravel()

array([1, 2, 3, 1, 2, 3, 2, 4, 4])

In [568]:
xarr.reshape(3,3)

array([[1, 2, 3],
       [1, 2, 3],
       [2, 4, 4]])

In [569]:
yarr = [[1,2,3],[3,1,2],[4,1,3]]
yarr = np.array(yarr)

In [570]:
xarr

array([[1, 2, 3],
       [1, 2, 3],
       [2, 4, 4]])

In [571]:
yarr

array([[1, 2, 3],
       [3, 1, 2],
       [4, 1, 3]])

In [572]:
xarr + yarr

array([[2, 4, 6],
       [4, 3, 5],
       [6, 5, 7]])

In [573]:
xarr * yarr

array([[ 1,  4,  9],
       [ 3,  2,  6],
       [ 8,  4, 12]])

In [574]:
np.sqrt(xarr)

array([[1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081],
       [1.41421356, 2.        , 2.        ]])

In [575]:
np.sqrt(yarr)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 1.        , 1.41421356],
       [2.        , 1.        , 1.73205081]])

In [576]:
xarr.sum()

np.int64(22)

In [578]:
xarr.max()

np.int64(4)

In [579]:
xarr.min()

np.int64(1)

In [580]:
xarr

array([[1, 2, 3],
       [1, 2, 3],
       [2, 4, 4]])

In [584]:
np.where(xarr<2)
#find th element

(array([0, 1]), array([0, 0]))

In [585]:
np.count_nonzero(xarr)
#counts all the non zero elements

9

In [586]:
np.nonzero(xarr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))